### ISSUE TITLE
AKI 3.7.6 Cannot connect to destination host. Client stuck at loading menu.

### ISSUE THREAD

**Issue by Verggy** [stayintarkov/SIT.Docker#10]
Image: stayintarkov/stayintarkov:3.7.6

`2024-04-27 19:38:18.773 +02:00|0.13.5.3.26535|Info|backend|---> Request HTTPS, id [1]: URL: http://0.0.0.0:6969/client/game/start, crc: .  
2024-04-27 19:38:18.790 +02:00|0.13.5.3.26535|Error|backend|<--- Error! HTTPS: http://0.0.0.0:6969/client/game/start, isNetworkError:True, isHttpError:False, responseCode:0
 responseHeaders:
error text: Cannot connect to destination host`
 
`2024-04-27 19:38:18.790 +02:00|0.13.5.3.26535|Warn|backend|Request http://0.0.0.0:6969/client/game/start will be retried after 41.97456 sec, retry:1 from retries:3 url:http://0.0.0.0:6969/client/game/start?retry=1 error:Backend error: Cannot connect to destination host`
,  
`2024-04-27 19:39:00.800 +02:00|0.13.5.3.26535|Error|backend|<--- Error! HTTPS: http://0.0.0.0:6969/client/game/start?retry=1, isNetworkError:True, isHttpError:False, responseCode:0
 responseHeaders:
error text: Cannot connect to destination host`
 
`2024-04-27 19:39:00.800 +02:00|0.13.5.3.26535|Warn|backend|Request http://0.0.0.0:6969/client/game/start will be retried after 66.92266 sec, retry:2 from retries:3 url:http://0.0.0.0:6969/client/game/start?retry=2 error:Backend error: Cannot connect to destination host`

any idea what to do?

**Comment by devbence** [comment]
setting ip to 0.0.0.0 means your server will listen on all available interface/ip on your machine, but you need to connect either to your internal/loopback ip. your friends should connect to your external/vpn ip.

i would also advise, upgrade. 3.7.6 was long time ago

**Comment by devbence** [comment]
+ this is not SIT.Docker issue, im closing this, join us on discord, we can help you set it up easily
