### ISSUE TITLE
Players not seeing hosted games in lobby.

### ISSUE THREAD

**Issue by Pr0xyWash0r** [stayintarkov/SIT.Docker#18]
### *Which* version you have issues with?
Using the prebuilt on Dockerhub

### *What* is this issue is about?
Players unable to see hosted games in lobby

### *When* does this occur?
In lobby

### *Are* you running the Docker as user or root?
root

### *How* do we replicate the issue?
We are using an OVH Debian 10 instance with docker pre-installed with 4GB of RAM.

### Expected behavior (i.e. solution)
Players should be able to see hosted games

### Other Comments
Ports appear to be open, test-netconnection returns TCPTestSucceeded:True for ports 6969-6971

when players enter lobby the server logs become flooded with the following message:

[Client Request] <PlayerIP> \coop\server\getAllForLocation
Error: incorrect header check
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at processChunkSync (node:zlib:457:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.inflateSync (node:zlib:809:14)
    at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
    at IncomingMessage.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: incorrect header check
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at processChunkSync (node:zlib:457:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.inflateSync (node:zlib:809:14)
    at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
    at IncomingMessage.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Snarklz** [comment]
This is interesting. 
I just came here to post about a similar issue, but we have not had issues with players being unable to see each other.
When we get this header error, it makes it so damage recording is turned off. Players can shoot, and be shot. Animations will play, ammo gets expended, but no health is deducted.
The code segment you listed under 'other comments' is exactly the same error report I get.
We are using the pre-built docker image, and I am running on Ubuntu 20.04 running as a user.

**Comment by devbence** [comment]
can you verify your port(s) are open? (6969, 6970, 6971)
check here: https://portchecker.io/ 
or with nmap:
nmap -p6969-6971 ip.addr.ess

**Comment by Pr0xyWash0r** [comment]
> can you verify your port(s) are open? (6969, 6970, 6971) check here: https://portchecker.io/ or with nmap: nmap -p6969-6971 ip.addr.ess
![Screenshot 2024-05-25 103103](https://github.com/stayintarkov/SIT.Docker/assets/10350835/e389aff2-4564-415e-9046-f9c9a302a032)

**Comment by Snarklz** [comment]
![image](https://github.com/stayintarkov/SIT.Docker/assets/170812743/c24138d9-fce1-48f1-8579-e9d564685ced)

**Comment by devbence** [comment]
and server is.. 1.6.5 with 1.11 client?

**Comment by Pr0xyWash0r** [comment]
Server is 1.6.5, but the client is 1.10. SIT.Manager does not appear to have an upgrade showing for me to 1.11

**Comment by kapdon** [comment]
change `image: stayintarkov/stayintarkov` to `image: stayintarkov/stayintarkov:3.8.0.4`
which is the last 1.10 build. 

enable the dev build setting flag in SIT Manager if you want to use 1.11 pre-release which is stayintarkov/stayintarkov:latest

**Comment by SystemFiles** [comment]
Can confirm that using the `3.8.0.4` tag solved this issue for me! It was a version mismatch. The latest points to the pre-release 1.11 as stated above
