### ISSUE TITLE
getAllForLocation

### ISSUE THREAD

**Issue by GenkiPL** [stayintarkov/SIT.Docker#19]
### *Which* version you have issues with?

spt-aki 3.8.3 github
### *What* is this issue is about?

damage not working, coop not working, 
### *When* does this occur?

when on server we host a raid
### *Are* you running the Docker as user or root?

root

### Other Comments

 [Client Request] 89.68.61.234 \coop\server\getAllForLocation
sitcoop  | Error: incorrect header check
sitcoop  | Error: incorrect header check
sitcoop  |     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
sitcoop  |     at processChunkSync (node:zlib:457:12)
sitcoop  |     at zlibBufferSync (node:zlib:178:12)
sitcoop  |     at Object.inflateSync (node:zlib:809:14)
sitcoop  |     at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
sitcoop  |     at IncomingMessage.emit (node:events:518:28)
sitcoop  |     at endReadableNT (node:internal/streams/readable:1696:12)
sitcoop  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
sitcoop  | Error: incorrect header check
sitcoop  | Error: incorrect header check
sitcoop  |     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
sitcoop  |     at processChunkSync (node:zlib:457:12)
sitcoop  |     at zlibBufferSync (node:zlib:178:12)
sitcoop  |     at Object.inflateSync (node:zlib:809:14)
sitcoop  |     at IncomingMessage.<anonymous> (/snapshot/src/servers/http/AkiHttpListener.ts:69:60)
sitcoop  |     at IncomingMessage.emit (node:events:518:28)
sitcoop  |     at endReadableNT (node:internal/streams/readable:1696:12)
sitcoop  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by devbence** [comment]
you need to use 1.11 client with the 1.11 server
