### ISSUE TITLE
Cant host online game

### ISSUE THREAD

**Issue by Traceur70** [stayintarkov/SIT.Docker#2]
Hi,
First thanks you very much for your work.
Now I can play solo, but if I host a game, I cant jump or fire.

I saw this error on the logs
```
2024-01-14 00:38:56 Checking server authorization for profile: e454cd2956fed4095388ba57
2024-01-14 00:38:56 e454cd2956fed4095388ba57 is not authorized in server: pmc5359ec5d13fcd8292fbec8a8
```

So I supposed AuthorizedUsers is not well updated when using SIT.Docker
```ts
console.log(`Checking server authorization for profile: ${profileId}`);
if(this.AuthorizedUsers.findIndex(x => x == profileId) === -1)
{
   console.log(`${profileId} is not authorized in server: ${this.ServerId}`);
    
   WebSocketHandler.Instance.closeWebSocketSession(profileId, CoopMatchEndSessionMessages.WEBSOCKET_TIMEOUT_MESSAGE);
   return;
}
```

FYI
- SIT Client Version 1.9.8766.40295
- EFT Client Version 0.13.9.1.27622
- SIT.Docker commit 9cb97edf
- I can reach `http://<public-ip>:6969` and `http://<public-ip>:6970`
- I have already done post forwarding on my router and allow connection in my firewall (I can host games and play with friends when using SPT & SIT without Docker)
- I have follow the README and I already use Docker for other project
- Logs are here : [logs-2024-01-13.log](https://github.com/stayintarkov/SIT.Docker/files/13931208/logs-2024-01-13.log)

Thanks

**Comment by devbence** [comment]
Hi!
Possible solution, please try with an additional build-arg, as:
`--build-arg SIT=022caac252205e1b9ca30b3610884ad1b05d0dc1`

Reason:
The 0.14 branch was merged to [SIT.Aki-Server-Mod](https://github.com/stayintarkov/SIT.Aki-Server-Mod)'s master, and the script pulls the latest of everything if not set otherwise. 

I'll set this to the readme as well.

**Comment by Traceur70** [comment]
Sorry, unstable commit from SIT coop mod
Here is a PR with a little more precise readme : https://github.com/stayintarkov/SIT.Docker/pull/3
