### ISSUE TITLE
Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by tR4z8r** [stayintarkov/SIT.Docker#4]
I got a game login error!
Error: Value cannot be null. Parameter name: source

**Comment by devbence** [comment]
mind hopping on discord and ask there in support? im not sure if its relevant to SIT.Docker. 
I'm not closing the issue yet, if you sure this is something regarding SIT.Docker, let me know!

**Comment by tR4z8r** [comment]
The matter is settled!
