### ISSUE TITLE
Command line freezes

### ISSUE THREAD

**Issue by tR4z8r** [stayintarkov/SIT.Docker#6]
Before the story: I launched a game server, invited a friend, we entered the game and played for about 5 minutes then the command line of the game server froze and of course in the game is no longer working shooting and do not spawn bots, but if I click refresh command line then the game not hangs. Question why often hangs the server?????

**Comment by devbence** [comment]
how much memory your server have? 
you can try to run the server binary on linux within a screen if containerized sit uses too much resource. 
usually when this happens, a memory error follows in the logs.

**Comment by tR4z8r** [comment]
My server has 16GB of RAM

**Comment by tR4z8r** [comment]
> how much memory your server have? you can try to run the server binary on linux within a screen if containerized sit uses too much resource. usually when this happens, a memory error follows in the logs.

My server has 16GB of RAM. Ubuntu 20.04
The console just freezes and bots are not generated, but when you press Enter in the cmd console, bots start to be generated normally and so every time. there is no error in the logs!

**Comment by devbence** [comment]
what enter you need to press in what console? 

are you running your server in docker???

**Comment by tR4z8r** [comment]
> what enter you need to press in what console?
> 
> are you running your server in docker???

I start the server with the docker start sitcoop command! If I have Ubuntu linux (without desktop) installed how do I install only the server to make it work as well?

**Comment by devbence** [comment]
i still dont know what console are you referring to, i suppose you run the server by itself then, this is "expected" behaviour if you click into the window, this is not because the build, nor docker.

if you have a docker engine running on your machine, you can just copy the 3 commands from the readme, and you are good to go

**Comment by tR4z8r** [comment]
> Я до сих пор не знаю, о какой консоли вы говорите, я предполагаю, что вы запускаете сервер сам по себе, это "ожидаемое" поведение, если вы нажимаете в окно, это не из-за сборки, или Docker.
> 
> Если на вашем компьютере работает механизм Docker, вы можете просто скопировать 3 команды из файла readme, и все готово

I already have a compiled server! I compiled it in Windows. In Windows 10, the server works fine. How do I move this server to Ubuntu so it can run through Docker?

**Comment by devbence** [comment]
> I already have a compiled server! I compiled it in Windows. In Windows 10, the server works fine. How do I move this server to Ubuntu so it can run through Docker?

build a server on linux too, start it once, then copy your `profiles` and `mods` from `user` (from the windows machine)

**Comment by ovingiv** [comment]
With you running it in Ubuntu Server, are you using `screen`?
