### ISSUE TITLE
Unraid and cap letters

### ISSUE THREAD

**Issue by kirito92** [stayintarkov/SIT.Docker#7]
Is it possible to have the docker name lowercased, because unraid won't let me use uppercase letters when trying to pull from github, unraid is a os based of linux and doesn't have all of the sudo comands like apt get

**Comment by devbence** [comment]
hey, you can use small cap afaik. it worked for me ```git clone https://github.com/stayintarkov/sit.docker.git```

**Comment by kirito92** [comment]
yeah, that wasn't the issue i'm still learning all this, i'm working on
pushing a image of the docker to docker hub as we speak

**Comment by kirito92** [comment]
kirito92/sitcoop is the repository for anyone wanting a updated image for
unraid

**Comment by ollebro** [comment]
Did you manage to get this to work on Unraid? I dont understand how to push the build-arg for the container in unraid.

**Comment by kirito92** [comment]
[image: image.png]
yes, i did have it working, although have not updated it in a while, if ur
interested let me know and i'll look into updating it to w.e is current

**Comment by kirito92** [comment]
although, git hub no, i had to build it on unraid using docker build, then
push it to docker hub, which is what unraid uses to pull updates for docker
containers.

**Comment by ollebro** [comment]
no thats fine, I managed to figure it out in the end, thanks!
