### ISSUE TITLE
Image not running on Debian (Port already in use [by itself])

### ISSUE THREAD

**Issue by Jan-NiklasB** [stayintarkov/SIT.Docker#8]
Hey,
I tried to reach out on you on Discord but sadly you require phone validation, but I'm not going to share my number with Discord... anyways.

I tried to setup this docker image on a Debian root server running Docker and Portainer.
The build process already showed up tons of deprecation messages, but since I see this quite often that's may not be the problem.
When running the container after first startup and config it errors with the message:

```
Starting the server to generate all the required files
StayInTarkov Docker by bullet
Started copying files to your volume/directory.. Please wait.
Files copied to your machine in 9 seconds.
Follow the instructions to proceed!
Commit hash: 4b8b62ae8344cbc2a42135ca9225089809832873
Build date: 1710608732033
┌─────────────────────────────────────┐
│ SPT-AKI 3.8.0                       │
│ https://discord.sp-tarkov.com       │
│                                     │
│ This work is free of charge         │
│ If you paid money, you were scammed │
│ Commercial use is prohibited        │
└─────────────────────────────────────┘
ModLoader: loading 1 server mods...
COOP MOD: Coop Config loaded.
COOP MOD: Coop Config Loading >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Mod: sit-coop version: 1.6.0 by: Paulov loaded
Server: executing startup callbacks...
Importing database...
SIT: TCP Relay WebSocket is listening on 6969
SIT: TCP Nat Helper WebSocket is listening on 6970
Database import finished.
Port 6969 is already in use, check if the server is already running
Error: listen EADDRINUSE: address already in use 0.0.0.0:6969
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at doListen (node:net:2069:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

using `lsof -i :6969` in the container and on the host I found the container itself using this port already and on the host only the container using it when running.

So it seems to me that there's something wrong with the image under Linux, since using the same version of this repo under Win10 gives me less build steps and runs fine.

Another SIDE NOTE:  since I'm not sure if I missed something, is there an option to tell the container which ports to use for new matches?
Since the log tells me that the match is running on port 6972, but that isn't feed to the host and therefor in my test I can't connect to it while normal login works.

Any help would be really appreciated.
Thanks
Jan-Niklas

**Comment by devbence** [comment]
hey,
mind trying with the 1.6.1 args? i included those in the latest readme

you can open any ports, if you want to open 6971 and 6972 too, use the run command like this:
```
docker run --pull=never -v $PWD/server:/opt/server -p 6969:6969 -p 6970:6970 -p 6971:6971 -p 6972:6972 -it --name sitcoop sitcoop
```

**Comment by Jan-NiklasB** [comment]
> hey, mind trying with the 1.6.1 args? i included those in the latest readme
> 
> you can open any ports, if you want to open 6971 and 6972 too, use the run command like this:
> 
> ```
> docker run --pull=never -v $PWD/server:/opt/server -p 6969:6969 -p 6970:6970 -p 6971:6971 -p 6972:6972 -it --name sitcoop sitcoop
> ```

Hey, thanks for the response.
I will try it.

I tried already the -p parameter to open more ports, but that shifted, for whatever reason, the default com-ports to these, without any changes to the config files.

I will comeback here to report if this worked for me.
